### ISSUE TITLE
Undefined variable when request fails

### ISSUE THREAD

**Issue by bymaximus** [niiknow/bvtnet-items-provider#1]
Line 374 variable `rsp` is undefined, should use `error` variable

https://github.com/niiknow/bvtnet-items-provider/blob/cb11c9ad1985da58b57b79b344432c87daa9ef8c/src/index.js#L370-L378

**Comment by noogen** [comment]
Thanks, it has been fixed.

**Comment by bymaximus** [comment]
Awesome, thank you
