### ISSUE TITLE
Pagination not working in manner

### ISSUE THREAD

**Issue by dolarpatel** [niiknow/bvtnet-items-provider#2]
When I select for 2 or 3 number in pagination data is loading fine but still 1 is selected on third page.

**Comment by noogen** [comment]
Can you provide demo/example?  It's working on the demo:  https://niiknow.github.io/bvtnet-items-provider/

**Comment by noogen** [comment]
Thanks, it's not a bug in the app but in the demo.  We're binding the currentPage value to two different components: b-table and b-pagination; And the b-pagination is setting/resetting this value.   The demo is fixed and document/readme updated: https://github.com/niiknow/bvtnet-items-provider/blob/a38b59e8a763c751ed4714b1e831befc1b29e80b/example/app.vue#L58

Explain: The action of initializing a b-pagination in combination with total-rows value will reset/set currentPage to 1.  We have to put in a v-if to make sure only to initialize b-pagination when we have valid totalRows.

**Comment by dolarpatel** [comment]
Yes, later I checked and found variable update issue. It's working fine.

Thanks
