### ISSUE TITLE
wrong records info when there are 0 results after applying filter

### ISSUE THREAD

**Issue by aliameen91** [niiknow/bvtnet-items-provider#4]
when there are no records after applying the filter, the record info on the bottom of the table is wrong.

this is caused by the following condition set in the src code.

   		that.totalRows = myData.recordsFiltered || myData.recordsTotal

here if the recordsFiltered is 0 then the totalRows will be set to recordsTotal which is wrong.

please fix this.

**Comment by noogen** [comment]
Done and published.
