### ISSUE TITLE
Cannot set the search field value to empty string

### ISSUE THREAD

**Issue by aliameen91** [niiknow/bvtnet-items-provider#5]

**Comment by noogen** [comment]
How so?  Need more info/details (sample code) for reproduction?    In the demo here, you can see to empty in search field and click go to get all result:  https://niiknow.github.io/bvtnet-items-provider/

**Comment by aliameen91** [comment]
@noogen hey, sorry i opened this issue in a hurry as I was in the middle of development.
the issue is not with the global search but with column search. initialize a column searchfield to empty string, and you will see in the network tab, the request that is sent will show [object object] instead of empty string. so its broken somehow.

**Comment by noogen** [comment]
Try version 1.0.7
